// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ChatReq struct {
	Question  string `json:"question"`
	SessionId string `json:"sessionId,optional"`
}

type ChatResp struct {
	Answer    string `json:"answer"`
	SessionId string `json:"sessionId,optional"`
}

type PingResp struct {
	Message string `json:"message"`
}

type SearchReq struct {
	Query string `json:"query"`
	TopK  int    `json:"topK,optional"`
}

type SearchResp struct {
	Results []SearchResult `json:"results"`
}

type SearchResult struct {
	DocId   string  `json:"docId"`
	Content string  `json:"content"`
	Score   float64 `json:"score"`
}

type UploadDocRequest struct {
	RequestId string `json:"requestId"`
}

type UploadDocRespose struct {
	DocId   string `json:"docId"`
	Url     string `json:"url"`
	Version int    `json:"version"`
}
