// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ChatReq struct {
	Question  string `json:"question"`
	SessionId string `json:"sessionId,optional"`
}

type ChatResp struct {
	Answer    string `json:"answer"`
	SessionId string `json:"sessionId,optional"`
}

type PingResp struct {
	Message string `json:"message"`
}

type SearchReq struct {
	Query string `json:"query"`
	TopK  int    `json:"topK,optional"`
}

type SearchResp struct {
	Results []SearchResult `json:"results"`
}

type SearchResult struct {
	DocId   string  `json:"docId"`
	Content string  `json:"content"`
	Score   float64 `json:"score"`
}

type UploadDocRequest struct {
	RequestId string `json:"requestId"`
}

type UploadDocRespose struct {
	DocId   string `json:"docId"`
	Url     string `json:"url"`
	Version int    `json:"version"`
}

// ---------- analytics 统计接口 ----------

type AnalyticsEventStat struct {
	Total     int64   `json:"total"`
	AvgMs     float64 `json:"avgMs"`
	MaxMs     int64   `json:"maxMs"`
	ErrorRate float64 `json:"errorRate"`
}

type AnalyticsOverviewResp struct {
	Chat   *AnalyticsEventStat `json:"chat"`
	Search *AnalyticsEventStat `json:"search"`
	Upload *AnalyticsEventStat `json:"upload"`
}

type AnalyticsTrendsReq struct {
	Days int `form:"days,optional"`
}

type AnalyticsTrendPoint struct {
	Date  string  `json:"date"`
	Total int64   `json:"total"`
	AvgMs float64 `json:"avgMs"`
	P95Ms float64 `json:"p95Ms"`
}

type AnalyticsTrendsResp struct {
	Points []AnalyticsTrendPoint `json:"points"`
}

type AnalyticsSlowReq struct {
	Limit int `form:"limit,optional"`
}

type AnalyticsSlowItem struct {
	EventTime  string `json:"eventTime"`
	EventType  string `json:"eventType"`
	DurationMs int64  `json:"durationMs"`
	Success    bool   `json:"success"`
	TraceID    string `json:"traceId"`
	Detail     string `json:"detail"`
}

type AnalyticsSlowResp struct {
	Items []AnalyticsSlowItem `json:"items"`
}

// ---------- 文档列表/详情 ----------

type DocItem struct {
	DocID     string `json:"docId"`
	Title     string `json:"title"`
	DocType   string `json:"docType"`
	FileUrl   string `json:"fileUrl"`
	CreatedAt string `json:"createdAt"`
	Version   int    `json:"version"`
}

type DocListReq struct {
	Page int `form:"page,optional"`
	Size int `form:"size,optional"`
}

type DocListResp struct {
	Items    []DocItem `json:"items"`
	Total    int64     `json:"total"`
	Page     int       `json:"page"`
	PageSize int       `json:"pageSize"`
}

type DocDetailResp struct {
	DocItem
	Content string `json:"content"`
}
