// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/yourname/know/cmd/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chat",
				Handler: ChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/doc/upload",
				Handler: UploadDocHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/search",
				Handler: SearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
